version: '3.8'

services:
  revenue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./revenue/:/usr/src/revenue/
    ports:
      - 5000:5000

  db:
    image: postgis/postgis:12-3.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nory
    ports:
      - 5432:5432

volumes:
  postgres_data:
